// <auto-generated />
using EFCodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCodeFirst.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200418120418_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCodeFirst.Entity.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            UserId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 2,
                            UserId = 2
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EFCodeFirst.Entity.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductNum")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "烤鸭",
                            ProductNum = 30
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "火腿",
                            ProductNum = 40
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "啤酒",
                            ProductNum = 50
                        });
                });

            modelBuilder.Entity("EFCodeFirst.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "张三"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "李四"
                        },
                        new
                        {
                            UserId = 3,
                            UserName = "麻五"
                        });
                });

            modelBuilder.Entity("EFCodeFirst.Entity.Order", b =>
                {
                    b.HasOne("EFCodeFirst.Entity.Product", "Product")
                        .WithOne("Order")
                        .HasForeignKey("EFCodeFirst.Entity.Order", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCodeFirst.Entity.User", "User")
                        .WithOne("Order")
                        .HasForeignKey("EFCodeFirst.Entity.Order", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
